# Generated by Django 5.2.7 on 2026-07-04 14:47

import django.contrib.postgres.fields
import django.contrib.postgres.indexes
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0004_add_user_fks'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='analyticssnapshot',
            name='snapshot_entity_metric_date_idx',
        ),
        migrations.RemoveIndex(
            model_name='analyticssnapshot',
            name='snapshot_date_granularity_idx',
        ),
        migrations.RemoveIndex(
            model_name='cargo',
            name='cargo_shipment_hazmat_idx',
        ),
        migrations.RemoveIndex(
            model_name='cargo',
            name='cargo_type_idx',
        ),
        migrations.RemoveIndex(
            model_name='cargo',
            name='cargo_gross_weight_idx',
        ),
        migrations.RemoveIndex(
            model_name='cargo',
            name='cargo_reefer_temp_partial_idx',
        ),
        migrations.RemoveIndex(
            model_name='carrier',
            name='carrier_mode_active_idx',
        ),
        migrations.RemoveIndex(
            model_name='company',
            name='company_type_active_idx',
        ),
        migrations.RemoveIndex(
            model_name='port',
            name='port_type_active_idx',
        ),
        migrations.RemoveIndex(
            model_name='port',
            name='port_country_type_idx',
        ),
        migrations.RemoveIndex(
            model_name='portcall',
            name='portcall_route_sequence_idx',
        ),
        migrations.RemoveIndex(
            model_name='portcall',
            name='portcall_port_sched_arr_idx',
        ),
        migrations.RemoveIndex(
            model_name='portcall',
            name='portcall_vessel_voyage_idx',
        ),
        migrations.RemoveIndex(
            model_name='portcall',
            name='portcall_delay_hours_partial_idx',
        ),
        migrations.RemoveIndex(
            model_name='route',
            name='route_carrier_status_idx',
        ),
        migrations.RemoveIndex(
            model_name='route',
            name='route_lane_status_idx',
        ),
        migrations.RemoveIndex(
            model_name='route',
            name='route_effective_range_idx',
        ),
        migrations.RemoveIndex(
            model_name='shipment',
            name='shipment_carrier_status_idx',
        ),
        migrations.RemoveIndex(
            model_name='shipment',
            name='shipment_shipper_status_eta_idx',
        ),
        migrations.RemoveIndex(
            model_name='shipment',
            name='shipment_departure_date_idx',
        ),
        migrations.RemoveIndex(
            model_name='shipment',
            name='shipment_estimated_arrival_idx',
        ),
        migrations.RemoveIndex(
            model_name='shipment',
            name='shipment_active_carr_eta_idx',
        ),
        migrations.RemoveIndex(
            model_name='shipment',
            name='shipment_exception_idx',
        ),
        migrations.RemoveIndex(
            model_name='trackingevent',
            name='tracking_shipment_event_time_idx',
        ),
        migrations.RemoveIndex(
            model_name='trackingevent',
            name='tracking_port_event_time_idx',
        ),
        migrations.RemoveIndex(
            model_name='trackingevent',
            name='tracking_event_type_time_idx',
        ),
        migrations.RemoveIndex(
            model_name='trackingevent',
            name='tracking_unresolved_exc_idx',
        ),
        migrations.RemoveField(
            model_name='shipment',
            name='created_by',
        ),
        migrations.AlterField(
            model_name='analyticssnapshot',
            name='dimensions',
            field=models.JSONField(blank=True, db_column='dimensions', default=dict, help_text='Breakdown dimensions e.g. {carrier_mode: SEA, origin_country: CN}'),
        ),
        migrations.AlterField(
            model_name='analyticssnapshot',
            name='entity_id',
            field=models.UUIDField(blank=True, db_column='entity_id', help_text='FK to the entity being measured; NULL for GLOBAL snapshots', null=True),
        ),
        migrations.AlterField(
            model_name='analyticssnapshot',
            name='id',
            field=models.UUIDField(db_column='id', default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='analyticssnapshot',
            name='metric_key',
            field=models.CharField(db_column='metric_key', help_text='Namespaced metric e.g. shipments.in_transit.count, delay.avg_hours', max_length=128),
        ),
        migrations.AlterField(
            model_name='cargo',
            name='container_number',
            field=models.CharField(blank=True, db_column='container_number', help_text='ISO 6346 container number e.g. MSCU1234567', max_length=11),
        ),
        migrations.AlterField(
            model_name='cargo',
            name='custom_attributes',
            field=models.JSONField(blank=True, db_column='custom_attributes', default=dict, help_text='Dangerous goods placards, CITES permits, phytosanitary data'),
        ),
        migrations.AlterField(
            model_name='cargo',
            name='description',
            field=models.CharField(db_column='description', help_text='Commodity description for customs and B/L', max_length=512),
        ),
        migrations.AlterField(
            model_name='cargo',
            name='gross_weight_kg',
            field=models.DecimalField(db_column='gross_weight_kg', decimal_places=3, help_text='Gross weight in kilograms; 3dp for sub-gram precision (pharma/jewellery)', max_digits=12),
        ),
        migrations.AlterField(
            model_name='cargo',
            name='id',
            field=models.UUIDField(db_column='id', default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='cargo',
            name='imdg_class',
            field=models.CharField(blank=True, db_column='imdg_class', help_text='IMDG hazard class e.g. 3, 6.1, 8', max_length=8),
        ),
        migrations.AlterField(
            model_name='cargo',
            name='package_type',
            field=models.CharField(blank=True, db_column='package_type', help_text='UNECE Rec 21 package type code e.g. CT (Carton), PL (Pallet)', max_length=32),
        ),
        migrations.AlterField(
            model_name='cargo',
            name='temperature_min_c',
            field=models.DecimalField(blank=True, db_column='temperature_min_c', decimal_places=2, help_text='Min setpoint °C for reefer cargo', max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='cargo',
            name='un_number',
            field=models.CharField(blank=True, db_column='un_number', help_text='UN number for hazardous goods e.g. 1263 (paint)', max_length=4),
        ),
        migrations.AlterField(
            model_name='cargo',
            name='volume_cbm',
            field=models.DecimalField(blank=True, db_column='volume_cbm', decimal_places=4, help_text='Volume in cubic meters; 4dp for LCL rating precision', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='carrier',
            name='carrier_code',
            field=models.CharField(db_column='carrier_code', help_text='SCAC (road/rail), IATA numeric (air), or custom code (sea)', max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='carrier',
            name='hub_ports',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=5), blank=True, db_column='hub_ports', default=list, help_text='UN/LOCODE array of primary hub ports/airports for this carrier', size=None),
        ),
        migrations.AlterField(
            model_name='carrier',
            name='id',
            field=models.UUIDField(db_column='id', default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='carrier',
            name='imo_number',
            field=models.CharField(blank=True, db_column='imo_number', help_text='IMO number for shipping lines; blank for non-sea carriers', max_length=7),
        ),
        migrations.AlterField(
            model_name='carrier',
            name='service_metadata',
            field=models.JSONField(blank=True, db_column='service_metadata', default=dict, help_text='Service strings, alliance membership, vessel fleet details'),
        ),
        migrations.AlterField(
            model_name='company',
            name='country_code',
            field=models.CharField(db_column='country_code', help_text='ISO 3166-1 alpha-2', max_length=2),
        ),
        migrations.AlterField(
            model_name='company',
            name='duns_number',
            field=models.CharField(blank=True, db_column='duns_number', help_text='D-U-N-S 9-digit business identifier', max_length=9),
        ),
        migrations.AlterField(
            model_name='company',
            name='id',
            field=models.UUIDField(db_column='id', default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='company',
            name='metadata',
            field=models.JSONField(blank=True, db_column='metadata', default=dict, help_text='Flexible per-company attributes: certifications, trade lanes, customs codes'),
        ),
        migrations.AlterField(
            model_name='company',
            name='tax_id',
            field=models.CharField(db_column='tax_id', help_text='VAT / EIN / TIN — jurisdiction-specific tax identifier', max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='port',
            name='country_code',
            field=models.CharField(db_column='country_code', help_text='ISO 3166-1 alpha-2', max_length=2),
        ),
        migrations.AlterField(
            model_name='port',
            name='iata_code',
            field=models.CharField(blank=True, db_column='iata_code', help_text='IATA 3-letter airport code; blank for seaports', max_length=3),
        ),
        migrations.AlterField(
            model_name='port',
            name='id',
            field=models.UUIDField(db_column='id', default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='port',
            name='timezone',
            field=models.CharField(db_column='timezone', help_text='IANA timezone identifier e.g. America/Los_Angeles', max_length=64),
        ),
        migrations.AlterField(
            model_name='port',
            name='un_locode',
            field=models.CharField(db_column='un_locode', help_text='UN/LOCODE 5-character code e.g. USLAX', max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='portcall',
            name='call_sequence',
            field=models.PositiveSmallIntegerField(db_column='call_sequence', help_text='Order of this port in the route itinerary (1-based)'),
        ),
        migrations.AlterField(
            model_name='portcall',
            name='id',
            field=models.UUIDField(db_column='id', default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='route',
            name='effective_until',
            field=models.DateField(blank=True, db_column='effective_until', help_text='NULL means indefinitely active', null=True),
        ),
        migrations.AlterField(
            model_name='route',
            name='id',
            field=models.UUIDField(db_column='id', default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='route',
            name='route_code',
            field=models.CharField(db_column='route_code', help_text='Internal route identifier e.g. CNSGH-USLAX-MSC-W1', max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='route',
            name='transshipment_ports',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=5), blank=True, db_column='transshipment_ports', default=list, help_text='Ordered array of UN/LOCODE transshipment hubs', size=None),
        ),
        migrations.AlterField(
            model_name='route',
            name='weekly_frequency',
            field=models.PositiveSmallIntegerField(db_column='weekly_frequency', default=1, help_text='Number of sailings/flights per week'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='actual_arrival',
            field=models.DateTimeField(blank=True, db_column='actual_arrival', help_text='ATA — set on final delivery event', null=True),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='bill_of_lading',
            field=models.CharField(blank=True, db_column='bill_of_lading', help_text='Master B/L number issued by carrier', max_length=64),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='currency_code',
            field=models.CharField(db_column='currency_code', default='USD', help_text='ISO 4217 currency code', max_length=3),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='custom_attributes',
            field=models.JSONField(blank=True, db_column='custom_attributes', default=dict, help_text='Flexible shipper/forwarder defined attributes'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='declared_value',
            field=models.DecimalField(blank=True, db_column='declared_value', decimal_places=2, help_text='Cargo declared value in USD for customs/insurance', max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='departure_date',
            field=models.DateTimeField(blank=True, db_column='departure_date', help_text='Actual or estimated departure (ETD)', null=True),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='estimated_arrival',
            field=models.DateTimeField(blank=True, db_column='estimated_arrival', help_text='ETA at destination port', null=True),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='freight_cost',
            field=models.DecimalField(blank=True, db_column='freight_cost', decimal_places=2, help_text='Agreed freight rate in USD', max_digits=14, null=True),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='house_bill_of_lading',
            field=models.CharField(blank=True, db_column='house_bill_of_lading', help_text='House B/L issued by freight forwarder', max_length=64),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='hs_codes',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=10), blank=True, db_column='hs_codes', default=list, help_text='HS tariff codes for contained commodities', size=None),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='id',
            field=models.UUIDField(db_column='id', default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='incoterms',
            field=models.CharField(blank=True, db_column='incoterms', help_text='Incoterms 2020 code e.g. FOB, CIF, DAP', max_length=3),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='purchase_order_refs',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=64), blank=True, db_column='purchase_order_refs', default=list, help_text='PO numbers this shipment fulfils (multi-PO consolidations)', size=None),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=64), blank=True, db_column='tags', default=list, help_text='Operational tags: priority, project, lane', size=None),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='tracking_number',
            field=models.CharField(db_column='tracking_number', help_text='Public-facing tracking reference (customer-visible)', max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='trackingevent',
            name='event_time',
            field=models.DateTimeField(db_column='event_time', help_text='When the event physically occurred (not when it was recorded)'),
        ),
        migrations.AlterField(
            model_name='trackingevent',
            name='id',
            field=models.UUIDField(db_column='id', default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='trackingevent',
            name='location_description',
            field=models.CharField(blank=True, db_column='location_description', help_text='Free-text location for non-port events (e.g. truck GPS position)', max_length=255),
        ),
        migrations.AlterField(
            model_name='trackingevent',
            name='port',
            field=models.ForeignKey(blank=True, db_column='port_id', help_text='Port where event occurred; NULL for non-port events', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tracking_events', to='logistics.port'),
        ),
        migrations.AlterField(
            model_name='trackingevent',
            name='raw_payload',
            field=models.JSONField(blank=True, db_column='raw_payload', default=dict, help_text='Original message from carrier API/EDI for audit and reprocessing'),
        ),
        migrations.AlterField(
            model_name='trackingevent',
            name='recorded_at',
            field=models.DateTimeField(auto_now_add=True, db_column='recorded_at', help_text='When this record was inserted (system time)'),
        ),
        migrations.AlterField(
            model_name='trackingevent',
            name='source_system',
            field=models.CharField(blank=True, db_column='source_system', help_text='EDI system, API provider, or manual entry identifier', max_length=64),
        ),
        migrations.AlterField(
            model_name='trackingevent',
            name='supersedes',
            field=models.ForeignKey(blank=True, db_column='supersedes_id', help_text='Points to the event this one corrects; enables audit trail', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='superseded_by', to='logistics.trackingevent'),
        ),
        migrations.AddIndex(
            model_name='analyticssnapshot',
            index=django.contrib.postgres.indexes.BTreeIndex(fields=['entity_type', 'entity_id', 'metric_key', 'snapshot_date'], name='snapshot_entity_metric_date_idx'),
        ),
        migrations.AddIndex(
            model_name='analyticssnapshot',
            index=django.contrib.postgres.indexes.BTreeIndex(fields=['snapshot_date', 'granularity', 'entity_type'], name='snapshot_date_granularity_idx'),
        ),
        migrations.AddIndex(
            model_name='cargo',
            index=django.contrib.postgres.indexes.BTreeIndex(fields=['shipment_id', 'is_hazmat'], name='cargo_shipment_hazmat_idx'),
        ),
        migrations.AddIndex(
            model_name='cargo',
            index=django.contrib.postgres.indexes.BTreeIndex(fields=['cargo_type'], name='cargo_type_idx'),
        ),
        migrations.AddIndex(
            model_name='cargo',
            index=django.contrib.postgres.indexes.BTreeIndex(fields=['gross_weight_kg'], name='cargo_gross_weight_idx'),
        ),
        migrations.AddIndex(
            model_name='cargo',
            index=django.contrib.postgres.indexes.BTreeIndex(condition=models.Q(('temperature_min_c__isnull', False)), fields=['temperature_min_c'], name='cargo_reefer_temp_partial_idx'),
        ),
        migrations.AddIndex(
            model_name='carrier',
            index=django.contrib.postgres.indexes.BTreeIndex(fields=['mode', 'is_active'], name='carrier_mode_active_idx'),
        ),
        migrations.AddIndex(
            model_name='company',
            index=django.contrib.postgres.indexes.BTreeIndex(fields=['company_type', 'is_active'], name='company_type_active_idx'),
        ),
        migrations.AddIndex(
            model_name='port',
            index=django.contrib.postgres.indexes.BTreeIndex(fields=['port_type', 'is_active'], name='port_type_active_idx'),
        ),
        migrations.AddIndex(
            model_name='port',
            index=django.contrib.postgres.indexes.BTreeIndex(fields=['country_code', 'port_type'], name='port_country_type_idx'),
        ),
        migrations.AddIndex(
            model_name='portcall',
            index=django.contrib.postgres.indexes.BTreeIndex(fields=['route_id', 'call_sequence'], name='portcall_route_sequence_idx'),
        ),
        migrations.AddIndex(
            model_name='portcall',
            index=django.contrib.postgres.indexes.BTreeIndex(fields=['port_id', 'scheduled_arrival'], name='portcall_port_sched_arr_idx'),
        ),
        migrations.AddIndex(
            model_name='portcall',
            index=django.contrib.postgres.indexes.BTreeIndex(fields=['vessel_name', 'voyage_number'], name='portcall_vessel_voyage_idx'),
        ),
        migrations.AddIndex(
            model_name='portcall',
            index=django.contrib.postgres.indexes.BTreeIndex(condition=models.Q(('arrival_delay_hours__isnull', False)), fields=['arrival_delay_hours'], name='portcall_delay_hours_partial_idx'),
        ),
        migrations.AddIndex(
            model_name='route',
            index=django.contrib.postgres.indexes.BTreeIndex(fields=['carrier_id', 'status'], name='route_carrier_status_idx'),
        ),
        migrations.AddIndex(
            model_name='route',
            index=django.contrib.postgres.indexes.BTreeIndex(fields=['origin_port_id', 'destination_port_id', 'status'], name='route_lane_status_idx'),
        ),
        migrations.AddIndex(
            model_name='route',
            index=django.contrib.postgres.indexes.BTreeIndex(fields=['effective_from', 'effective_until'], name='route_effective_range_idx'),
        ),
        migrations.AddIndex(
            model_name='shipment',
            index=django.contrib.postgres.indexes.BTreeIndex(fields=['carrier_id', 'status'], name='shipment_carrier_status_idx'),
        ),
        migrations.AddIndex(
            model_name='shipment',
            index=django.contrib.postgres.indexes.BTreeIndex(fields=['shipper_id', 'status', 'estimated_arrival'], name='shipment_shipper_status_eta_idx'),
        ),
        migrations.AddIndex(
            model_name='shipment',
            index=django.contrib.postgres.indexes.BTreeIndex(fields=['departure_date'], name='shipment_departure_date_idx'),
        ),
        migrations.AddIndex(
            model_name='shipment',
            index=django.contrib.postgres.indexes.BTreeIndex(fields=['estimated_arrival'], name='shipment_estimated_arrival_idx'),
        ),
        migrations.AddIndex(
            model_name='shipment',
            index=django.contrib.postgres.indexes.BTreeIndex(condition=models.Q(('status__in', ['BOOKED', 'IN_TRANSIT', 'AT_PORT'])), fields=['carrier_id', 'estimated_arrival'], name='shipment_active_carr_eta_idx'),
        ),
        migrations.AddIndex(
            model_name='shipment',
            index=django.contrib.postgres.indexes.BTreeIndex(condition=models.Q(('status__in', ['EXCEPTION', 'CUSTOMS_HOLD'])), fields=['created_at'], name='shipment_exception_idx'),
        ),
        migrations.AddIndex(
            model_name='trackingevent',
            index=django.contrib.postgres.indexes.BTreeIndex(fields=['shipment_id', 'event_time'], name='tracking_shipment_event_time_idx'),
        ),
        migrations.AddIndex(
            model_name='trackingevent',
            index=django.contrib.postgres.indexes.BTreeIndex(fields=['port_id', 'event_time'], name='tracking_port_event_time_idx'),
        ),
        migrations.AddIndex(
            model_name='trackingevent',
            index=django.contrib.postgres.indexes.BTreeIndex(fields=['event_type', 'event_time'], name='tracking_event_type_time_idx'),
        ),
        migrations.AddIndex(
            model_name='trackingevent',
            index=django.contrib.postgres.indexes.BTreeIndex(condition=models.Q(('is_exception', True), ('exception_resolved', False)), fields=['shipment_id', 'event_time'], name='tracking_unresolved_exc_idx'),
        ),
    ]
