# Generated by Django 5.2.7 on 2026-07-04 14:47

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('logistics', '0005_remove_analyticssnapshot_snapshot_entity_metric_date_idx_and_more'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='carrier',
            field=models.ForeignKey(blank=True, db_column='carrier_id', help_text='The carrier this user works for. NULL for non-carrier users.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_users', to='logistics.carrier'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='company',
            field=models.ForeignKey(blank=True, db_column='company_id', help_text='The company this user represents. NULL for internal staff.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='logistics.company'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(db_column='email', help_text='Primary identity. Used for login and all communications.', max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='id',
            field=models.UUIDField(db_column='id', default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_email_verified',
            field=models.BooleanField(db_column='is_email_verified', default=False, help_text='Unverified users cannot access write endpoints.'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_superuser',
            field=models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='failed_login_count',
            field=models.PositiveIntegerField(db_column='failed_login_count', default=0, help_text='Mirrored from django-axes for API exposure. Axes manages the actual lockout.'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='id',
            field=models.UUIDField(db_column='id', default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='last_login_ip',
            field=models.GenericIPAddressField(blank=True, db_column='last_login_ip', help_text='IP of last successful login — for audit and anomaly detection', null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='notification_preferences',
            field=models.JSONField(blank=True, db_column='notification_preferences', default=dict, help_text='Per-user notification settings: email, sms, webhook toggles'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phone_number',
            field=models.CharField(blank=True, db_column='phone_number', help_text='E.164 format e.g. +12125551234', max_length=20),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='timezone',
            field=models.CharField(db_column='timezone', default='UTC', help_text='IANA timezone identifier', max_length=64),
        ),
    ]
